# Frontend nixpacks.toml for Railway deployment
providers = ['node']

[variables]
NODE_VERSION = '20'

[phases.setup]
nixPkgs = ['nodejs_20']

[phases.install]
cmd = 'npm ci'

[phases.build] 
cmd = '''
export REACT_APP_API_URL=https://web-production-bf0b7.up.railway.app
export REACT_APP_API_BASE_URL=https://web-production-bf0b7.up.railway.app
npm run build
'''

[start]
cmd = 'npx serve -s build -l $PORT'