providers = ['python']

[variables]
NIXPACKS_PYTHON_VERSION = '3.11'

[phases.setup]
nixPkgs = ['python311', 'python311Packages.pip', 'curl', 'gnupg']
aptPkgs = ['unixodbc-dev']

[phases.install]
cmd = '''
# Install Microsoft ODBC Driver 18 for SQL Server
curl -fsSL https://packages.microsoft.com/keys/microsoft.asc | sudo gpg --dearmor -o /usr/share/keyrings/microsoft-prod.gpg
echo "deb [arch=amd64,arm64,armhf signed-by=/usr/share/keyrings/microsoft-prod.gpg] https://packages.microsoft.com/ubuntu/22.04/prod jammy main" | sudo tee /etc/apt/sources.list.d/mssql-release.list
sudo apt-get update
sudo ACCEPT_EULA=Y apt-get install -y msodbcsql18

# Install Python requirements
cd backend && pip install -r requirements.txt
'''

[phases.build]
cmd = 'echo "Build phase completed"'

[start]
cmd = 'cd backend && python run_server.py'
