[variables]
NIXPACKS_PYTHON_VERSION = '3.11'

[phases.setup]
nixpkgs = ["python311", "python311Packages.pip", "curl"]

[phases.install]
cmds = [
    # Install Python and ODBC dependencies
    "apt-get update",
    "apt-get install -y python3 python3-pip curl gnupg2 apt-transport-https ca-certificates",
    # Add Microsoft repository (Debian 11 - Nixpacks uses Debian)
    "curl https://packages.microsoft.com/keys/microsoft.asc | apt-key add -",
    "curl https://packages.microsoft.com/config/debian/11/prod.list > /etc/apt/sources.list.d/mssql-release.list",
    "apt-get update",
    # Install ODBC Driver 17 (more stable than 18 for Debian)
    "ACCEPT_EULA=Y apt-get install -y msodbcsql17 unixodbc-dev",
    # Install Python requirements
    "cd backend && python3 -m pip install -r requirements.txt --break-system-packages"
]

[phases.build]
cmds = [
    "echo '=== QuantumCertify Build Phase ==='",
    "odbcinst -q -d || echo 'ODBC driver check'",
    "cd backend && python3 startup_test.py || echo 'Startup test completed - continuing deployment'",
    "echo '=== Build phase completed ==='"
]

[start]
cmd = 'cd backend && python3 run_server.py'
