providers = ['python']
   
[variables]
NIXPACKS_PYTHON_VERSION = '3.11'

[phases.setup]
nixPkgs = ['python311', 'python311Packages.pip', 'curl', 'gnupg2', 'apt']

[phases.install]
cmd = '''
# Update package list
apt-get update

# Install Microsoft ODBC Driver 18 for SQL Server on Railway's Linux
curl -fsSL https://packages.microsoft.com/keys/microsoft.asc | gpg --dearmor -o /usr/share/keyrings/microsoft-prod.gpg
curl -fsSL https://packages.microsoft.com/config/ubuntu/22.04/prod.list | tee /etc/apt/sources.list.d/mssql-release.list
apt-get update
ACCEPT_EULA=Y apt-get install -y msodbcsql18 unixodbc-dev

# Install Python requirements
cd backend && pip install -r requirements.txt
'''

[phases.build]
cmd = 'echo "Build phase completed"'

[start]
cmd = 'cd backend && python run_server.py'
