[build]
builder = "nixpacks"

[deploy]
startCommand = "cd backend && python3 run_server.py"
healthcheckPath = "/health"
healthcheckTimeout = 300
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10

[environments.production]
variables = { ENVIRONMENT = "production", RAILWAY_ENVIRONMENT = "production" }
