# Root Railway configuration for monorepo
[services]
backend = { source = "backend", build = "pip install -r requirements.txt", start = "python run_server.py" }
frontend = { source = "frontend", build = "npm run build", start = "npx serve -s build -l $PORT" }

[environments.production.variables]
NODE_ENV = "production"
REACT_APP_API_URL = "https://web-production-bf0b7.up.railway.app"